# .github/workflows/pr-approval.yml
name: PR Approval

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests
      run: echo "Running tests.." # Replace with actual test commands

  wait_for_approval:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Approval needed
      run: echo "Waiting for approval"
    - name: Approve PR
      if: github.event.inputs.approved == 'true'
      run: echo "PR approved"


# name: Cats 😺

# on:
#   pull_request_target:
#     types:
#       - opened
#       - reopened

# jobs:
#   aCatForCreatingThePullRequest:
#     name: A cat for your effort!
#     runs-on: ubuntu-latest
#     steps:
#       - uses: ruairidhwm/action-cats@1.0.1
#         with:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}